### ISSUE TITLE
SLS-001 | UX and accessibility feature for offline/online use

### ISSUE THREAD

**Issue by JavaBoii** [JavaBoii/PixelPrecision#4]
### Project Number
SLS-001

### Task
Creating an easy to understand Setup process for defining 
- either the side or **monitor name** to be used by the program _[See image 1]_
- either the side or **modem name** to be used by the program _[See image 1]_

<details>
    <summary>Image 1</summary>
    <img src="https://github.com/JavaBoii/PixelPrecision/assets/79570962/3e47796c-7fda-48be-968a-c5a77131f1f2" alt="Image1" height="150">
</details>

And a simple menu to define, edit or change channels of the program _[See image 2]_
<details>
    <summary>Image 2</summary>
    <img src="https://github.com/JavaBoii/PixelPrecision/assets/79570962/79dc9adb-3c88-4d8b-aa0b-62c3c07846c6" alt="Image2" height="250">
</details>

---
### TODO:
- [x] MonitoringStation
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
- [x] PowderChargeManager
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
- [x] Safeguard
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
- [x] ItemManager
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
- [x] OrderManagementSystem
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
- [x] Sender
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
- [x] RoleAssignmentScript
  - [x] moved to new UX design
  - [x] all constants can be changed dynamicly
