### ISSUE TITLE
GCM-000 | Project restructure to pave way for future updates

### ISSUE THREAD

**Issue by JavaBoii** [JavaBoii/PixelPrecision#6]
**MergeRequests:**
#

---
**Description:**

Restructure project repository and `README.md`
- make it easier to develop project once `CAAS ( Computer Assisted Artillery System )` gets added.
- make navigating the Documentation easier by seperating the 2 projects with visual context (e.g. individual project logo so people can, at a glance, jump to their desired code in my project )
---
**Tasks**

- [ ] Project restructure complete
- [ ] Project Icons created
- [ ] README.md updated
